### PR TITLE
Remove obsolete Ant-build and the embedded libraries

### PR DESCRIPTION
**Pull request by ibauersachs**
We use Maven now, no need to keep the embededd libraries and (probably outdated) ant-stuff around.

### CODE REVIEW

**Comment by lyubomir** [comment]
Ah, @emcho may want to approve the removal of the Ant script because it contains run targets which we don't have in the Maven script. Otherwise, I'm OK to merge this PR.

**Comment by ibauersachs** [comment]
The run-* targets? I'd say if anybody needs those, they are easily launched from an IDE without Ant. If they're really needed we can add them as Maven profiles using exec-maven-plugin.

**Comment by lyubomir** [comment]
Yup, I agree, @ibauersachs. I wanted to make sure that @emcho is mentioned before we proceed with the merge.

**Comment by emcho** [comment]
Having run scripts is an important part for ice4j development so, before merging this, could we please make sure we have alternatives in maven?

**Comment by ibauersachs** [comment]
I've updated the PR and added the run targets.

**Pull request merged**
