### PR TITLE
handover IOException to higher level is needed

### PR DESCRIPTION
**Pull request by ubivent-seuffert**
the DelegatingDatagramSocket needs to hand a send IOException to a higher level, otherwise the socket can not be closed on send failures

### CODE REVIEW

**Comment by ubivent-seuffert** [comment]
CLA signed.

**Comment by ibauersachs** [comment]
Hmm. Is that dirty hack still necessary? Last I've read is that OSX now has a working IPv6 stack.

**Comment by bgrozev** [comment]
Is there any reason to not simplify this to match for NoRouteToHostException in the catch clause? We're still swallowing exceptions that are not IOException.

**Comment by ibauersachs** [comment]
I doubt that this check is still necessary at all. But I don't have a Mac (and neither an IPv6 network) to test.

**Pull request merged**
